### ISSUE TITLE
ux_mode, hosted_doamin and redirect_uri options missing

### ISSUE THREAD

**Issue by jrosa-neoassist** [rmartide/vue-google-login#1]
I tried passing these options with the plugin for security reasons, but it doesn't recognize them.

**Comment by thomasleveil** [comment]
try something like:

```html
<button @click="login">log in</button>

```

```js
...
    methods: {
        login() {
            Vue.GoogleAuth.then(auth2 => {
                auth2.signIn({
                    ux_mode: xxxxx,
                    hosted_domain: "xxx.tld",
                    redirect_uri: "https://xxxxx"
                });
            });
        })
    }
...
```

**Comment by rmartide** [comment]
Hey, I'm really sorry it took me this long, I've been very very with work.

I don't know if thomasleveil's answer was helpful but I want to say now the component allows the usage of all params options by default.

Again sorry and thanks pointing it out.

I will close the issue now.

**Comment by thomasleveil** [comment]
@rmartide since you made a breaking change, you should change the major number of the version. It should be `2.0.0` and not `1.0.4`. Users having `^1.0.3` in their packages.json dependencies could accidently upgrade to `1.0.4` by using `npm upgrade`. See [Semver](https://semver.org/)

**Comment by rmartide** [comment]
gotchu, I can do that, thanks
