### ISSUE TITLE
Shows whether or not I am signed in to Google and not my site

### ISSUE THREAD

**Issue by gpowerone** [rmartide/vue-google-login#10]
Perhaps I am missing something-is there any way to configure this button so that it shows that I am logged into my site or not? 

With the default configuration it says "Signed in With Google" whether or not I am signed into my site or not. If I log out of Google, it says "Sign In". 

I have the button and my Client ID configured correctly, as far as I know.

**Comment by rmartide** [comment]
Hi, that button is rendered by google, I just checked the behaviour and it says "Sign in With Google" when you are not singed in and "Signed in With Google" when you are signed in.

I also tested to log in and log out with the custom buttons, without using the one renderer by google, and the text updates as soon as you log in and log out.

For the full button config you can check this next link:
[https://developers.google.com/identity/sign-in/web/reference#gapisignin2renderid_options](https://developers.google.com/identity/sign-in/web/reference#gapisignin2renderid_options)
