### ISSUE TITLE
Button does not appear

### ISSUE THREAD

**Issue by AlexanderMz** [rmartide/vue-google-login#11]
Hi, 

Cuando compilo mi WepApp hecha en Quasar-framework a android o electron-win23 el botón de inicio no aparece para hacer Login...

gracias.

**Comment by rmartide** [comment]
Hey,

Ostras! Ojalá pudiera ayudarte pero es como si me hablaras en chino. No tengo ni idea de esos frameworks. Puedo intentar investigar un poco pero sinceramente no prometo nada.

Un saludo.

**Comment by AlexanderMz** [comment]
> Hey,
> 
> Ostras! Ojalá pudiera ayudarte pero es como si me hablaras en chino. No tengo ni idea de esos frameworks. Puedo intentar investigar un poco pero sinceramente no prometo nada.
> 
> Un saludo.

Te lo agradezco @rmartide estaré atento

**Comment by ricardoxlopes** [comment]
Hi,

I had the same problem but with AdonisJS, adding the following code in index.js solved my problem.

```
import GoogleLogin from 'vue-google-login'

Vue.use(GoogleLogin)
```
