### ISSUE TITLE
option to add scope

### ISSUE THREAD

**Issue by altoP** [rmartide/vue-google-login#16]
Hello, is there an option to add scope?
tried to add it to params: scope: "https://www.googleapis.com/auth/gmail.readonly",

**Comment by rmartide** [comment]
Hi, yes, you did it the right way, I just tried and it worked.

`params: {
	client_id: CLIENT_ID,
	scope: 'https://www.googleapis.com/auth/cloud-platform.read-only'
}`

Result: 
![image](https://user-images.githubusercontent.com/37620405/85436100-cac04780-b588-11ea-9736-2afbf64098c0.png)

It's really small but the last bit is the added scope.

**Comment by altoP** [comment]
Tn'x
Its actually worked once after I posted and then again I don't see the **https://www.googleapis.com/auth/gmail.readonly**
Maybe some verification issues with google.
