### ISSUE TITLE
How to set restriced uris?

### ISSUE THREAD

**Issue by gustawdaniel** [rmartide/vue-google-login#17]
In google credentials there is:

+ Authorized redirect URIs 

How to configure this value?

**Comment by rmartide** [comment]
As far as I know the authorized redirect URIs are set when creating or editing the OAuth 2.0 client id credentials.

**Comment by gustawdaniel** [comment]
I have error:

```
{error: "idpiframe_initialization_failed", details: "Not a valid origin for the client: http://localhos…itelist this origin for your project's client ID."}
```

In case of `Meteor` packages to integrate with google login there was mentioned in documentation

https://guide.meteor.com/accounts.html#oauth-configuration

> Redirect URL. On the OAuth provider’s side, you’ll need to specify a redirect URL. The URL will look like: https://www.example.com/_oauth/facebook. Replace facebook with the name of the service you are using. Note that you will need to configure two URLs - one for your production app, and one for your development environment, where the URL might be something like http://localhost:3000/_oauth/facebook.

**Comment by rmartide** [comment]
Yeah, the error is pointing to the client ID credentials.

To be honest I don't that much about all the parameters.

If you want to try adding the redirect_uri you just need to add it to the params object.

```
data() {
		return {
			params: {
				client_id: CLIENT_ID,
				redirect_uri: "..."
			},
          }
}
```

I wish I could help you more. Last time I did something alike it was trial and error and it was a long time ago.
