### ISSUE TITLE
idpiframe_initialization_failed error

### ISSUE THREAD

**Issue by leokyohan** [rmartide/vue-google-login#20]
Hello 

I was trying to use this plugin for implementing google login in my Vue project.
But I'm getting the below error.
"idpiframe_initialization_failed", details: "Not a valid origin for the client: http://localhost:8080…whitelist this origin for your project's client ID."}

I checked my cookie settings, 3rd party cookies are allowed by default.
I already have my localhost in google credentials in OAuth 2.0 Client IDs.

I'm getting this error from vue-google-login project in the console when I'm loading the project. Then when I try to sign in after clicking login button, once I give the password, it goes to onFailure() method instead of onSuccess(googleUser) method. Any hints what might be going wrong in my case?

**Comment by leokyohan** [comment]
Is this behavior anything related to https://www.chromestatus.com/feature/5088147346030592 this update by google? Because it was working fine for me earlier, and now it stopped working.

**Comment by rmartide** [comment]
That error seems to be related with your client ID configuration, but if it was working fine earlier I have no idea to be honest.

I wish I could be of more help.

**Comment by leokyohan** [comment]
But this is the error I'm getting.

A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

any idea  if we are missing something in the google API request?

**Comment by rmartide** [comment]
Sorry I have no idea.

If I recall correctly that's a recent change and I haven't encountered that error it so I don't know.

It seems google doesn't like cookies from third party applications or something like that.

I did a quick search and it seems a lot of people are having issues right now with google sing-in in chrome.

Since this search confirms that is a chrome or configuration issue and is not related with the component I will proceed to close the issue.
