### ISSUE TITLE
Help pls!

### ISSUE THREAD

**Issue by AlexanderMz** [rmartide/vue-google-login#9]
![imagen](https://user-images.githubusercontent.com/12861422/69871303-70743800-1280-11ea-9f92-75f3a7983f0c.png)

**Comment by rmartide** [comment]
Oh, did you add GoogleLogin to the components property? On the same component you are importing it.

I just realized I didn't add that part to the readme.

![image](https://user-images.githubusercontent.com/37620405/69877014-56a71500-12c1-11ea-8710-146d180b09c8.png)

**Comment by rmartide** [comment]
I updated the readme just in case it happens to someone else.

**Comment by AlexanderMz** [comment]
Work!
Gracias!!

**Comment by jonalxh** [comment]
It is happening to me and I've configured the component as you said before. Any idea?
